[package]
name = "fe_oxy"
version = "0.1.0"
authors = ["Konrad <konrad_here@hotmail.com>"]

[[bin]]
name = "main"
doc = false
test = false

[dependencies]
gfx = "*"
gfx_window_glutin = "*"
glutin = "*"
